export const depositContract = [
  {
    inputs: [
      { internalType: "address", name: "_evvmAddress", type: "address" },
      { internalType: "address", name: "_verifier", type: "address" },
      { internalType: "bytes32", name: "_imageId", type: "bytes32" },
      {
        internalType: "bytes32",
        name: "_expectedNotaryKeyFingerprint",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_expectedQueriesHash",
        type: "bytes32",
      },
      { internalType: "address", name: "_paymentToken", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AuthorizationAlreadyUsed", type: "error" },
  { inputs: [], name: "DepositAmountMustBeGreaterThanZero", type: "error" },
  { inputs: [], name: "Expired", type: "error" },
  { inputs: [], name: "InsufficientBalance", type: "error" },
  { inputs: [], name: "InvalidContributions", type: "error" },
  { inputs: [], name: "InvalidDepositAmount", type: "error" },
  { inputs: [], name: "InvalidListing", type: "error" },
  { inputs: [], name: "InvalidNotaryKeyFingerprint", type: "error" },
  { inputs: [], name: "InvalidQueriesHash", type: "error" },
  { inputs: [], name: "InvalidSignature", type: "error" },
  { inputs: [], name: "InvalidUrl", type: "error" },
  { inputs: [], name: "OrderWasntDelivered", type: "error" },
  { inputs: [], name: "PrincipalTokenIsNotWithdrawable", type: "error" },
  { inputs: [], name: "WrongCredentials", type: "error" },
  { inputs: [], name: "ZKProofVerificationFailed", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "authorizer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "nonce",
        type: "bytes32",
      },
    ],
    name: "AuthorizationUsed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          { internalType: "string", name: "url", type: "string" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "address", name: "shopper", type: "address" },
          {
            internalType: "bytes32",
            name: "privateCredentials",
            type: "bytes32",
          },
        ],
        indexed: false,
        internalType: "struct Treasury.Listing",
        name: "listing",
        type: "tuple",
      },
      { indexed: false, internalType: "bytes32", name: "id", type: "bytes32" },
    ],
    name: "ListingCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          { internalType: "string", name: "url", type: "string" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "address", name: "shopper", type: "address" },
          {
            internalType: "bytes32",
            name: "privateCredentials",
            type: "bytes32",
          },
        ],
        indexed: false,
        internalType: "struct Treasury.Listing",
        name: "listing",
        type: "tuple",
      },
      { indexed: false, internalType: "bytes32", name: "id", type: "bytes32" },
      {
        indexed: false,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
    ],
    name: "ListingFinalized",
    type: "event",
  },
  {
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "EXPECTED_NOTARY_KEY_FINGERPRINT",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "EXPECTED_QUERIES_HASH",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "IMAGE_ID",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAYMENT_TOKEN",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TRANSFER_WITH_AUTHORIZATION_TYPEHASH",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VERIFIER",
    outputs: [
      { internalType: "contract IRiscZeroVerifier", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "bytes32", name: "", type: "bytes32" },
    ],
    name: "authorizationState",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "url", type: "string" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "address", name: "shopper", type: "address" },
          {
            internalType: "bytes32",
            name: "privateCredentials",
            type: "bytes32",
          },
        ],
        internalType: "struct Treasury.Listing",
        name: "listing",
        type: "tuple",
      },
    ],
    name: "calculateId",
    outputs: [{ internalType: "bytes32", name: "id", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "fullName", type: "string" },
          { internalType: "string", name: "emailAddress", type: "string" },
          { internalType: "string", name: "homeAddress", type: "string" },
          { internalType: "string", name: "city", type: "string" },
          { internalType: "string", name: "country", type: "string" },
          { internalType: "string", name: "zip", type: "string" },
        ],
        internalType: "struct Treasury.PrivateCredentialsRaw",
        name: "rawCredentials",
        type: "tuple",
      },
    ],
    name: "createPrivateCredentials",
    outputs: [
      { internalType: "bytes32", name: "privateCredentials", type: "bytes32" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "depositor", type: "address" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "depositFrom",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "evvmAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "id", type: "bytes32" }],
    name: "fetchListing",
    outputs: [
      { internalType: "string", name: "url", type: "string" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "shopper", type: "address" },
      { internalType: "bytes32", name: "privateCredentials", type: "bytes32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "url", type: "string" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "address", name: "shopper", type: "address" },
          {
            internalType: "bytes32",
            name: "privateCredentials",
            type: "bytes32",
          },
        ],
        internalType: "struct Treasury.Listing",
        name: "listing",
        type: "tuple",
      },
    ],
    name: "list",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "id", type: "bytes32" },
      { internalType: "bytes", name: "purchaseData", type: "bytes" },
      { internalType: "bytes", name: "seal", type: "bytes" },
    ],
    name: "submitPurchase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
      { internalType: "uint256", name: "validAfter", type: "uint256" },
      { internalType: "uint256", name: "validBefore", type: "uint256" },
      { internalType: "bytes32", name: "nonce", type: "bytes32" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "transferWithAuthorization",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
