export const depositContract = [
  {
    type: "constructor",
    inputs: [
      { name: "_evvmAddress", type: "address", internalType: "address" },
      { name: "_verifier", type: "address", internalType: "address" },
      { name: "_imageId", type: "bytes32", internalType: "bytes32" },
      {
        name: "_expectedNotaryKeyFingerprint",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "_expectedQueriesHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      { name: "_paymentToken", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DOMAIN_SEPARATOR",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "EXPECTED_NOTARY_KEY_FINGERPRINT",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "EXPECTED_QUERIES_HASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "IMAGE_ID",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PAYMENT_TOKEN",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TRANSFER_WITH_AUTHORIZATION_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "VERIFIER",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IRiscZeroVerifier",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizationState",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calculateId",
    inputs: [
      {
        name: "listing",
        type: "tuple",
        internalType: "struct Treasury.Listing",
        components: [
          { name: "url", type: "string", internalType: "string" },
          { name: "productId", type: "string", internalType: "string" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "shopper", type: "address", internalType: "address" },
          {
            name: "privateCredentials",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
      },
    ],
    outputs: [{ name: "id", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "createPrivateCredentials",
    inputs: [
      {
        name: "rawCredentials",
        type: "tuple",
        internalType: "struct Treasury.PrivateCredentialsRaw",
        components: [
          { name: "fullName", type: "string", internalType: "string" },
          { name: "emailAddress", type: "string", internalType: "string" },
          { name: "homeAddress", type: "string", internalType: "string" },
          { name: "city", type: "string", internalType: "string" },
          { name: "country", type: "string", internalType: "string" },
          { name: "zip", type: "string", internalType: "string" },
        ],
      },
    ],
    outputs: [
      {
        name: "privateCredentials",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "depositFrom",
    inputs: [
      { name: "depositor", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "evvmAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fetchListing",
    inputs: [{ name: "id", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      { name: "url", type: "string", internalType: "string" },
      { name: "productId", type: "string", internalType: "string" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "shopper", type: "address", internalType: "address" },
      {
        name: "privateCredentials",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "list",
    inputs: [
      {
        name: "listing",
        type: "tuple",
        internalType: "struct Treasury.Listing",
        components: [
          { name: "url", type: "string", internalType: "string" },
          { name: "productId", type: "string", internalType: "string" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "shopper", type: "address", internalType: "address" },
          {
            name: "privateCredentials",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitPurchase",
    inputs: [
      { name: "id", type: "bytes32", internalType: "bytes32" },
      { name: "purchaseData", type: "bytes", internalType: "bytes" },
      { name: "seal", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferWithAuthorization",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
      { name: "validAfter", type: "uint256", internalType: "uint256" },
      { name: "validBefore", type: "uint256", internalType: "uint256" },
      { name: "nonce", type: "bytes32", internalType: "bytes32" },
      { name: "v", type: "uint8", internalType: "uint8" },
      { name: "r", type: "bytes32", internalType: "bytes32" },
      { name: "s", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AuthorizationUsed",
    inputs: [
      {
        name: "authorizer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "nonce",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ListingCreated",
    inputs: [
      {
        name: "listing",
        type: "tuple",
        indexed: false,
        internalType: "struct Treasury.Listing",
        components: [
          { name: "url", type: "string", internalType: "string" },
          { name: "productId", type: "string", internalType: "string" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "shopper", type: "address", internalType: "address" },
          {
            name: "privateCredentials",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
      },
      {
        name: "id",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ListingFinalized",
    inputs: [
      {
        name: "listing",
        type: "tuple",
        indexed: false,
        internalType: "struct Treasury.Listing",
        components: [
          { name: "url", type: "string", internalType: "string" },
          { name: "productId", type: "string", internalType: "string" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "shopper", type: "address", internalType: "address" },
          {
            name: "privateCredentials",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
      },
      {
        name: "id",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "buyer",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AuthorizationAlreadyUsed", inputs: [] },
  { type: "error", name: "DepositAmountMustBeGreaterThanZero", inputs: [] },
  { type: "error", name: "Expired", inputs: [] },
  { type: "error", name: "InsufficientBalance", inputs: [] },
  { type: "error", name: "InvalidContributions", inputs: [] },
  { type: "error", name: "InvalidDepositAmount", inputs: [] },
  { type: "error", name: "InvalidListing", inputs: [] },
  { type: "error", name: "InvalidNotaryKeyFingerprint", inputs: [] },
  { type: "error", name: "InvalidQueriesHash", inputs: [] },
  { type: "error", name: "InvalidSignature", inputs: [] },
  { type: "error", name: "InvalidUrl", inputs: [] },
  { type: "error", name: "OrderWasntDelivered", inputs: [] },
  { type: "error", name: "PrincipalTokenIsNotWithdrawable", inputs: [] },
  { type: "error", name: "WrongCredentials", inputs: [] },
  { type: "error", name: "ZKProofVerificationFailed", inputs: [] },
] as const;
